/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#d4c3c1",
        "surface-tint": "#795553",
        "outline": "#827472",
        "secondary-fixed": "#ffdcc5",
        "surface-dim": "#dfd9d1",
        "secondary": "#805533",
        "background": "#fff8f1",
        "on-secondary-fixed-variant": "#653d1e",
        "tertiary-container": "#492d19",
        "on-tertiary-fixed": "#2d1604",
        "primary-fixed": "#ffdad7",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#301400",
        "on-primary-fixed-variant": "#5f3e3c",
        "tertiary-fixed-dim": "#eabda0",
        "inverse-primary": "#eabcb8",
        "secondary-container": "#fdc39a",
        "error-container": "#ffdad6",
        "tertiary": "#311906",
        "surface-bright": "#fff8f1",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e8e1da",
        "on-tertiary": "#ffffff",
        "surface-container": "#f4ede5",
        "surface-container-lowest": "#ffffff",
        "primary": "#321716",
        "surface-container-low": "#f9f3eb",
        "error": "#ba1a1a",
        "surface": "#fff8f1",
        "on-error-container": "#93000a",
        "on-surface": "#1e1b17",
        "tertiary-fixed": "#ffdcc6",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#f4bb92",
        "on-tertiary-fixed-variant": "#5f402a",
        "primary-fixed-dim": "#eabcb8",
        "surface-container-high": "#eee7df",
        "primary-container": "#4a2c2a",
        "on-primary-fixed": "#2e1413",
        "on-background": "#1e1b17",
        "inverse-on-surface": "#f7f0e8",
        "on-primary-container": "#bd928f",
        "on-secondary-container": "#794e2e",
        "on-tertiary-container": "#bd9479",
        "surface-variant": "#e8e1da",
        "inverse-surface": "#33302b",
        "on-surface-variant": "#504443"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "grid-margin": "24px",
        "base": "8px",
        "max-width": "1280px",
        "section-gap-desktop": "120px",
        "section-gap-mobile": "64px",
        "grid-gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["DM Sans", "sans-serif"],
        "label-md": ["DM Sans", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["DM Sans", "sans-serif"]
      },
    },
  },
  plugins: [],
}
